<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'Evoweb\\EwLlxml2xliff\\' => array($typo3InstallDir . 'typo3conf/ext/ew_llxml2xliff/Classes'),
    'FluidTYPO3\\Vhs\\' => array($typo3InstallDir . 'typo3conf/ext/vhs/Classes'),
    'GridElementsTeam\\Gridelements\\' => array($typo3InstallDir . 'typo3conf/ext/gridelements/Classes'),
    'TeamDigital\\Bootstrapslider\\' => array($typo3InstallDir . 'typo3conf/ext/bootstrapslider/Classes'),
    'TeamDigital\\Sitepackage\\' => array($typo3InstallDir . 'typo3conf/ext/sitepackage/Classes'),
    'TeamDigital\\Tdtemplate\\' => array($typo3InstallDir . 'typo3conf/ext/tdtemplate/Classes'),
);
